data:
  image: busybox:latest
  volumes:
    - ./:/app
  entrypoint: tail -f /dev/null

app:
  image: yiisoftware/yii2-php:5.6-fpm
  #image: petun/yii2-php:0.3.2
  working_dir: /app
  volumes_from:
    - data
  volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  expose:
    - 9000
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"